# <b>PyCaret Classification Example (main components)<b>

Last Update: 02/01/2022

PyCaret Version: 2.2.3

Author: [Aurimas Aleksandras NausÄ—das](https://github.com/aurimas13)

# <b> Installation </b>

In [1]:
!pip install pycaret==2.2.3

Requirement already satisfied: pycaret==2.2.3 in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (2.2.3)
Requirement already satisfied: umap-learn in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from pycaret==2.2.3) (0.5.3)
Requirement already satisfied: yellowbrick>=1.0.1 in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from pycaret==2.2.3) (1.3.post1)
Requirement already satisfied: plotly>=4.4.1 in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from pycaret==2.2.3) (5.11.0)
Requirement already satisfied: pandas-profiling>=2.8.0 in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from pycaret==2.2.3) (3.5.0)
Requirement already satisfied: lightgbm>=2.3.1 in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from pycaret==2.2.3) (3.3.3)
Requirement already satisfied: pandas in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from pycaret==2.2.3) (1.3.5)
Requirement already satisfied: gensim in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from pycaret==2.2.3) (3.8.3)
Requirement already satisfied: cufflinks>=0.17.0 in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from pycaret==2.2.3) (0.17.3)
Requirement already satisfied: seaborn in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from pycaret==2.2.3) (0.11.2)
Requirement already satisfied: xgboost>=1.1.0 in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from pycaret==2.2.3) (1.6.1)
Requirement already satisfied: spacy in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from pycaret==2.2.3) (2.3.8)
Requirement already satisfied: catboost>=0.23.2 in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from pycaret==2.2.3) (1.0.4)
Requirement already satisfied: matplotlib in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from pycaret==2.2.3) (3.5.1)
Requirement already satisfied: imbalanced-learn>=0.7.0 in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from pycaret==2.2.3) (0.7.0)
Requirement already satisfied: textblob in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from pycaret==2.2.3) (0.17.1)
Requirement already satisfied: mlxtend in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from pycaret==2.2.3) (0.19.0)
Requirement already satisfied: scikit-learn==0.23.2 in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from pycaret==2.2.3) (0.23.2)
Requirement already satisfied: nltk in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from pycaret==2.2.3) (3.7)
Requirement already satisfied: scikit-plot in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from pycaret==2.2.3) (0.3.7)
Requirement already satisfied: IPython in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from pycaret==2.2.3) (8.3.0)
Requirement already satisfied: numpy>=1.17 in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from pycaret==2.2.3) (1.19.0)
Requirement already satisfied: joblib in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from pycaret==2.2.3) (1.2.0)
Requirement already satisfied: mlflow in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from pycaret==2.2.3) (2.0.1)
Requirement already satisfied: pyod in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from pycaret==2.2.3) (1.0.6)
Requirement already satisfied: kmodes>=0.10.1 in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from pycaret==2.2.3) (0.12.2)
Requirement already satisfied: ipywidgets in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from pycaret==2.2.3) (8.0.2)
Requirement already satisfied: wordcloud in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from pycaret==2.2.3) (1.8.2.2)
Requirement already satisfied: pyLDAvis in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from pycaret==2.2.3) (3.2.2)
Requirement already satisfied: scipy>=0.19.1 in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from scikit-learn==0.23.2->pycaret==2.2.3) (1.5.4)
Requirement already satisfied: threadpoolctl>=2.0.0 in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from scikit-learn==0.23.2->pycaret==2.2.3) (3.1.0)
Requirement already satisfied: six in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from catboost>=0.23.2->pycaret==2.2.3) (1.12.0)
Requirement already satisfied: graphviz in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from catboost>=0.23.2->pycaret==2.2.3) (0.20.1)
Requirement already satisfied: setuptools>=34.4.1 in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from cufflinks>=0.17.0->pycaret==2.2.3) (62.1.0)
Requirement already satisfied: colorlover>=0.2.1 in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from cufflinks>=0.17.0->pycaret==2.2.3) (0.3.0)
Requirement already satisfied: jedi>=0.16 in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from IPython->pycaret==2.2.3) (0.18.1)
Requirement already satisfied: pickleshare in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from IPython->pycaret==2.2.3) (0.7.5)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from IPython->pycaret==2.2.3) (3.0.33)
Requirement already satisfied: traitlets>=5 in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from IPython->pycaret==2.2.3) (5.1.1)
Requirement already satisfied: pexpect>4.3 in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from IPython->pycaret==2.2.3) (4.8.0)
Requirement already satisfied: pygments>=2.4.0 in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from IPython->pycaret==2.2.3) (2.12.0)
Requirement already satisfied: appnope in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from IPython->pycaret==2.2.3) (0.1.3)
Requirement already satisfied: matplotlib-inline in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from IPython->pycaret==2.2.3) (0.1.3)
Requirement already satisfied: decorator in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from IPython->pycaret==2.2.3) (5.1.1)
Requirement already satisfied: backcall in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from IPython->pycaret==2.2.3) (0.2.0)
Requirement already satisfied: stack-data in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from IPython->pycaret==2.2.3) (0.2.0)
Requirement already satisfied: jupyterlab-widgets~=3.0 in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from ipywidgets->pycaret==2.2.3) (3.0.3)
Requirement already satisfied: widgetsnbextension~=4.0 in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from ipywidgets->pycaret==2.2.3) (4.0.3)
Requirement already satisfied: ipykernel>=4.5.1 in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from ipywidgets->pycaret==2.2.3) (6.13.0)
Requirement already satisfied: wheel in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from lightgbm>=2.3.1->pycaret==2.2.3) (0.37.1)
Requirement already satisfied: python-dateutil>=2.7.3 in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from pandas->pycaret==2.2.3) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from pandas->pycaret==2.2.3) (2022.1)
Requirement already satisfied: PyYAML<6.1,>=5.0.0 in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from pandas-profiling>=2.8.0->pycaret==2.2.3) (5.4.1)
Requirement already satisfied: typeguard<2.14,>=2.13.2 in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from pandas-profiling>=2.8.0->pycaret==2.2.3) (2.13.3)
Requirement already satisfied: visions[type_image_path]==0.7.5 in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from pandas-profiling>=2.8.0->pycaret==2.2.3) (0.7.5)
Requirement already satisfied: tqdm<4.65,>=4.48.2 in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from pandas-profiling>=2.8.0->pycaret==2.2.3) (4.64.0)
Requirement already satisfied: statsmodels<0.14,>=0.13.2 in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from pandas-profiling>=2.8.0->pycaret==2.2.3) (0.13.2)
Requirement already satisfied: htmlmin==0.1.12 in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from pandas-profiling>=2.8.0->pycaret==2.2.3) (0.1.12)
Requirement already satisfied: multimethod<1.10,>=1.4 in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from pandas-profiling>=2.8.0->pycaret==2.2.3) (1.9)
Requirement already satisfied: phik<0.13,>=0.11.1 in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from pandas-profiling>=2.8.0->pycaret==2.2.3) (0.12.2)
Requirement already satisfied: pydantic<1.11,>=1.8.1 in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from pandas-profiling>=2.8.0->pycaret==2.2.3) (1.10.2)
Requirement already satisfied: requests<2.29,>=2.24.0 in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from pandas-profiling>=2.8.0->pycaret==2.2.3) (2.28.1)
Requirement already satisfied: jinja2<3.2,>=2.11.1 in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from pandas-profiling>=2.8.0->pycaret==2.2.3) (3.1.1)
Requirement already satisfied: networkx>=2.4 in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from visions[type_image_path]==0.7.5->pandas-profiling>=2.8.0->pycaret==2.2.3) (2.8.8)
Requirement already satisfied: attrs>=19.3.0 in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from visions[type_image_path]==0.7.5->pandas-profiling>=2.8.0->pycaret==2.2.3) (21.4.0)
Requirement already satisfied: tangled-up-in-unicode>=0.0.4 in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from visions[type_image_path]==0.7.5->pandas-profiling>=2.8.0->pycaret==2.2.3) (0.2.0)
Requirement already satisfied: imagehash in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from visions[type_image_path]==0.7.5->pandas-profiling>=2.8.0->pycaret==2.2.3) (4.3.1)
Requirement already satisfied: Pillow in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from visions[type_image_path]==0.7.5->pandas-profiling>=2.8.0->pycaret==2.2.3) (8.4.0)
Requirement already satisfied: pyparsing>=2.2.1 in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from matplotlib->pycaret==2.2.3) (3.0.8)
Requirement already satisfied: kiwisolver>=1.0.1 in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from matplotlib->pycaret==2.2.3) (1.4.2)
Requirement already satisfied: packaging>=20.0 in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from matplotlib->pycaret==2.2.3) (21.3)
Requirement already satisfied: fonttools>=4.22.0 in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from matplotlib->pycaret==2.2.3) (4.33.3)
Requirement already satisfied: cycler>=0.10 in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from matplotlib->pycaret==2.2.3) (0.11.0)
Requirement already satisfied: tenacity>=6.2.0 in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from plotly>=4.4.1->pycaret==2.2.3) (8.1.0)
Requirement already satisfied: smart-open>=1.8.1 in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from gensim->pycaret==2.2.3) (5.2.1)
Requirement already satisfied: gitpython<4,>=2.1.0 in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from mlflow->pycaret==2.2.3) (3.1.29)
Requirement already satisfied: databricks-cli<1,>=0.8.7 in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from mlflow->pycaret==2.2.3) (0.17.3)
Requirement already satisfied: gunicorn<21 in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from mlflow->pycaret==2.2.3) (20.1.0)
Requirement already satisfied: sqlparse<1,>=0.4.0 in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from mlflow->pycaret==2.2.3) (0.4.3)
Requirement already satisfied: Flask<3 in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from mlflow->pycaret==2.2.3) (2.2.2)
Requirement already satisfied: querystring-parser<2 in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from mlflow->pycaret==2.2.3) (1.2.4)
Requirement already satisfied: pyarrow<11,>=4.0.0 in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from mlflow->pycaret==2.2.3) (6.0.1)
Requirement already satisfied: click<9,>=7.0 in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from mlflow->pycaret==2.2.3) (8.1.3)
Requirement already satisfied: docker<7,>=4.0.0 in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from mlflow->pycaret==2.2.3) (5.0.3)
Requirement already satisfied: cloudpickle<3 in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from mlflow->pycaret==2.2.3) (2.2.0)
Requirement already satisfied: protobuf<5,>=3.12.0 in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from mlflow->pycaret==2.2.3) (4.21.10)
Requirement already satisfied: shap<1,>=0.40 in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from mlflow->pycaret==2.2.3) (0.41.0)
Requirement already satisfied: importlib-metadata!=4.7.0,<6,>=3.7.0 in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from mlflow->pycaret==2.2.3) (4.11.3)
Requirement already satisfied: markdown<4,>=3.3 in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from mlflow->pycaret==2.2.3) (3.4.1)
Requirement already satisfied: sqlalchemy<2,>=1.4.0 in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from mlflow->pycaret==2.2.3) (1.4.44)
Requirement already satisfied: alembic<2 in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from mlflow->pycaret==2.2.3) (1.8.1)
Requirement already satisfied: entrypoints<1 in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from mlflow->pycaret==2.2.3) (0.4)
Requirement already satisfied: regex>=2021.8.3 in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from nltk->pycaret==2.2.3) (2022.10.31)
Requirement already satisfied: future in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from pyLDAvis->pycaret==2.2.3) (0.18.2)
Requirement already satisfied: numexpr in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from pyLDAvis->pycaret==2.2.3) (2.8.4)
Requirement already satisfied: funcy in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from pyLDAvis->pycaret==2.2.3) (1.17)
Requirement already satisfied: numba>=0.51 in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from pyod->pycaret==2.2.3) (0.54.1)
Requirement already satisfied: srsly<1.1.0,>=1.0.2 in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from spacy->pycaret==2.2.3) (1.0.6)
Requirement already satisfied: thinc<7.5.0,>=7.4.1 in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from spacy->pycaret==2.2.3) (7.4.6)
Requirement already satisfied: blis<0.8.0,>=0.4.0 in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from spacy->pycaret==2.2.3) (0.7.9)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from spacy->pycaret==2.2.3) (3.0.8)
Requirement already satisfied: wasabi<1.1.0,>=0.4.0 in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from spacy->pycaret==2.2.3) (0.10.1)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from spacy->pycaret==2.2.3) (1.0.9)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from spacy->pycaret==2.2.3) (2.0.7)
Requirement already satisfied: catalogue<1.1.0,>=0.0.7 in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from spacy->pycaret==2.2.3) (1.0.2)
Requirement already satisfied: plac<1.2.0,>=0.9.6 in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from spacy->pycaret==2.2.3) (1.1.3)
Requirement already satisfied: pynndescent>=0.5 in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from umap-learn->pycaret==2.2.3) (0.5.8)
Requirement already satisfied: Mako in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from alembic<2->mlflow->pycaret==2.2.3) (1.2.4)
Requirement already satisfied: oauthlib>=3.1.0 in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from databricks-cli<1,>=0.8.7->mlflow->pycaret==2.2.3) (3.2.2)
Requirement already satisfied: tabulate>=0.7.7 in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from databricks-cli<1,>=0.8.7->mlflow->pycaret==2.2.3) (0.9.0)
Requirement already satisfied: pyjwt>=1.7.0 in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from databricks-cli<1,>=0.8.7->mlflow->pycaret==2.2.3) (2.6.0)
Requirement already satisfied: websocket-client>=0.32.0 in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from docker<7,>=4.0.0->mlflow->pycaret==2.2.3) (1.3.2)
Requirement already satisfied: Werkzeug>=2.2.2 in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from Flask<3->mlflow->pycaret==2.2.3) (2.2.2)
Requirement already satisfied: itsdangerous>=2.0 in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from Flask<3->mlflow->pycaret==2.2.3) (2.1.2)
Requirement already satisfied: gitdb<5,>=4.0.1 in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from gitpython<4,>=2.1.0->mlflow->pycaret==2.2.3) (4.0.10)
Requirement already satisfied: zipp>=0.5 in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from importlib-metadata!=4.7.0,<6,>=3.7.0->mlflow->pycaret==2.2.3) (3.8.0)
Requirement already satisfied: psutil in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from ipykernel>=4.5.1->ipywidgets->pycaret==2.2.3) (5.9.0)
Requirement already satisfied: debugpy>=1.0 in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from ipykernel>=4.5.1->ipywidgets->pycaret==2.2.3) (1.6.0)
Requirement already satisfied: tornado>=6.1 in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from ipykernel>=4.5.1->ipywidgets->pycaret==2.2.3) (6.1)
Requirement already satisfied: jupyter-client>=6.1.12 in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from ipykernel>=4.5.1->ipywidgets->pycaret==2.2.3) (7.3.0)
Requirement already satisfied: nest-asyncio in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from ipykernel>=4.5.1->ipywidgets->pycaret==2.2.3) (1.5.5)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from jedi>=0.16->IPython->pycaret==2.2.3) (0.8.3)
Requirement already satisfied: MarkupSafe>=2.0 in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from jinja2<3.2,>=2.11.1->pandas-profiling>=2.8.0->pycaret==2.2.3) (2.1.1)
Requirement already satisfied: llvmlite<0.38,>=0.37.0rc1 in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from numba>=0.51->pyod->pycaret==2.2.3) (0.37.0)
Requirement already satisfied: ptyprocess>=0.5 in /Users/aurimasnausedas/opt/miniconda3/lib/python3.9/site-packages (from pexpect>4.3->IPython->pycaret==2.2.3) (0.7.0)

In [2]:
# Check version
from pycaret.utils import version
print('Confirm PyCaret version 2.2.X?')
print('PyCaret Version: ', version())

Confirm PyCaret version 2.2.X?
PyCaret Version:  2.2.3

# 1. <b> Data Repository<b>

In [3]:
from pycaret.datasets import get_data
index = get_data('index')

,Dataset,Data Types,Default Task,Target Variable 1,Target Variable 2,# Instances,# Attributes,Missing Values
0,anomaly,Multivariate,Anomaly Detection,None,None,1000,10,N
1,france,Multivariate,Association Rule Mining,InvoiceNo,Description,8557,8,N
2,germany,Multivariate,Association Rule Mining,InvoiceNo,Description,9495,8,N
3,bank,Multivariate,Classification (Binary),deposit,None,45211,17,N
4,blood,Multivariate,Classification (Binary),Class,None,748,5,N
5,cancer,Multivariate,Classification (Binary),Class,None,683,10,N
6,credit,Multivariate,Classification (Binary),default,None,24000,24,N
7,diabetes,Multivariate,Classification (Binary),Class variable,None,768,9,N
8,electrical_grid,Multivariate,Classification (Binary),stabf,None,10000,14,N
9,employee,Multivariate,Classification (Binary),left,None,14999,10,N
10,heart,Multivariate,Classification (Binary),DEATH,None,200,16,N
11,heart_disease,Multivariate,Classification (Binary),Disease,None,270,14,N
12,hepatitis,Multivariate,Classification (Binary),Class,None,154,32,Y
13,income,Multivariate,Classification (Binary),income >50K,None,32561,14,Y
14,juice,Multivariate,Classification (Binary),Purchase,None,1070,15,N
15,nba,Multivariate,Classification (Binary),TARGET_5Yrs,None,1340,21,N
16,wine,Multivariate,Classification (Binary),type,None,6498,13,N
17,telescope,Multivariate,Classification (Binary),Class,None,19020,11,N
18,titanic,Multivariate,Classification (Binary),Survived,None,891,11,Y
19,us_presidential_election_results,Multivariate,Classification (Binary),party_winner,None,497,7,N
20,glass,Multivariate,Classification (Multiclass),Type,None,214,10,N
21,iris,Multivariate,Classification (Multiclass),species,None,150,5,N
22,poker,Multivariate,Classification (Multiclass),CLASS,None,100000,11,N
23,questions,Multivariate,Classification (Multiclass),Next_Question,None,499,4,N
24,satellite,Multivariate,Classification (Multiclass),Class,None,6435,37,N
25,CTG,Multivariate,Classification (Multiclass),NSP,None,2129,40,Y
26,asia_gdp,Multivariate,Clustering,None,None,40,11,N
27,elections,Multivariate,Clustering,None,None,3195,54,Y
28,facebook,Multivariate,Clustering,None,None,7050,12,N
29,ipl,Multivariate,Clustering,None,None,153,25,N
30,jewellery,Multivariate,Clustering,None,None,505,4,N
31,mice,Multivariate,Clustering,None,None,1080,82,Y
32,migration,Multivariate,Clustering,None,None,233,12,N
33,perfume,Multivariate,Clustering,None,None,20,29,N
34,pokemon,Multivariate,Clustering,None,None,800,13,Y
35,population,Multivariate,Clustering,None,None,255,56,Y
36,public_health,Multivariate,Clustering,None,None,224,21,N
37,seeds,Multivariate,Clustering,None,None,210,7,N
38,wholesale,Multivariate,Clustering,None,None,440,8,N
39,tweets,Text,NLP,tweet,None,8594,2,N
40,amazon,Text,NLP / Classification,reviewText,None,20000,2,N
41,kiva,Text,NLP / Classification,en,None,6818,7,N
42,spx,Text,NLP / Regression,text,None,874,4,N
43,wikipedia,Text,NLP / Classification,Text,None,500,3,N
44,automobile,Multivariate,Regression,price,None,202,26,Y
45,bike,Multivariate,Regression,cnt,None,17379,15,N
46,boston,Multivariate,Regression,medv,None,506,14,N
47,concrete,Multivariate,Regression,strength,None,1030,9,N
48,diamond,Multivariate,Regression,Price,None,6000,8,N
49,energy,Multivariate,Regression,Heating Load,Cooling Load,768,10,N
50,forest,Multivariate,Regression,area,None,517,13,N
51,gold,Multivariate,Regression,Gold_T+22,None,2558,121,N
52,house,Multivariate,Regression,SalePrice,None,1461,81,Y
53,insurance,Multivariate,Regression,charges,None,1338,7,N
54,parkinsons,Multivariate,Regression,PPE,None,5875,22,N
55,traffic,Multivariate,Regression,traffic_volume,None,48204,8,N

In [4]:
data = get_data('juice')

,Id,Purchase,WeekofPurchase,StoreID,PriceCH,PriceMM,DiscCH,DiscMM,SpecialCH,SpecialMM,LoyalCH,SalePriceMM,SalePriceCH,PriceDiff,Store7,PctDiscMM,PctDiscCH,ListPriceDiff,STORE
0,1,CH,237,1,1.75,1.99,0.00,0.0,0,0,0.500000,1.99,1.75,0.24,No,0.000000,0.000000,0.24,1
1,2,CH,239,1,1.75,1.99,0.00,0.3,0,1,0.600000,1.69,1.75,-0.06,No,0.150754,0.000000,0.24,1
2,3,CH,245,1,1.86,2.09,0.17,0.0,0,0,0.680000,2.09,1.69,0.40,No,0.000000,0.091398,0.23,1
3,4,MM,227,1,1.69,1.69,0.00,0.0,0,0,0.400000,1.69,1.69,0.00,No,0.000000,0.000000,0.00,1
4,5,CH,228,7,1.69,1.69,0.00,0.0,0,0,0.956535,1.69,1.69,0.00,Yes,0.000000,0.000000,0.00,0

# 2. <b> Initialize Setup <b>

In [5]:
# Import classification from pycaret and make setup
from pycaret.classification import *
clf = setup(data, target='Purchase', session_id=123, log_experiment=True, experiment_name='juice1')

# 3. <b> Compare <b>

In [6]:
best_model = compare_models()

# 4. <b> Create Model<b>

In [7]:
lr = create_model('lr')

In [8]:
gbc = create_model('gbc')

In [9]:
rf = create_model('rf', fold = 5)

In [10]:
models(type='ensemble').index.tolist()

['rf', 'ada', 'gbc', 'et', 'xgboost', 'lightgbm', 'catboost']

In [11]:
ensemble_models = compare_models(include = models(type='ensemble').index.tolist(), fold = 3)

# 5. <b> Tune Hyperparameters<b>

In [12]:
tuned_lr = tune_model(lr)

In [13]:
tuned_rf = tune_model(rf)

# 6. <b> Ensemble Model<b>

In [14]:
bagged_gbc = ensemble_model(gbc)

In [15]:
boosted_gbc = ensemble_model(gbc, method='Boosting')

# 7. <b> Blend Models<b>

In [16]:
blender = blend_models(estimator_list = [boosted_gbc, bagged_gbc, tuned_rf], method='soft')

# 8. <b> Stack Models<b>

In [ ]:
stacker = stack_models(estimator_list = [boosted_gbc, bagged_gbc, tuned_rf], meta_model=rf)

IntProgress(value=0, description='Processing: ', max=6)

Initiated  . . . . . . . . . . . . . . . . . .             03:35:29
Status     . . . . . . . . . . . . . . . . . .     Finalizing Model
Estimator  . . . . . . . . . . . . . . . . . .  Stacking Classifier

Empty DataFrame
Columns: [Accuracy, AUC, Recall, Prec., F1, Kappa, MCC]
Index: []

# 9. <b> Analyze Model<b>

In [ ]:
plot_model(rf)

In [ ]:
plot_model(rf, plot = 'confusion_matrix')

+ Details of Confusion Matrix Metrics (TP, TN, FP, FN) found under Examples folder on my Github as Machine_Learning_with_Python_session_2.ipynb file.

In [ ]:
plot_model(rf, plot = 'feature')

In [ ]:
plot_model(rf, plot='pr')

In [ ]:
plot_model(rf, plot = 'class_report')

+ Details of Precision, Recall and F1 Metrics found under Examples folder on my Github as Machine_Learning_with_Python_session_2.ipynb file.

In [ ]:
evaluate_model(rf)

# 10. <b> Interpret Model<b>

In [ ]:
catboost = create_model('catboost', cross_validation=False)

In [ ]:
interpret_model(catboost)

In [ ]:
interpret_model(catboost, plot = 'correlation')

In [ ]:
interpret_model(catboost, plot = 'reason', observation = 12)

# 11. <b>AutoML()<b>

In [ ]:
best = automl(optimize = 'Recall')
best

# 12. <b>Predict Model<b>

In [ ]:
pred_holdouts = predict_model(lr)
pred_holdouts.head()

In [ ]:
new_data = data.copy()
new_data.drop(['Purchase'], axis=1, inplace=True)
predict_new = predict_model(best, data=new_data)
predict_new.head(10)
# data.head(10)

# 13. <b>Save / Load Model<b>

In [ ]:
save_model(best, model_name='best-model')

In [ ]:
load_bestmodel = load_model('best-model')
print(load_bestmodel)

# 14. <b> Evaluate Model<b>

In [ ]:
evaluate_model(best)